[workspace]
resolver = "2"
members = [
    "evs-codec-sys",
    "opencore-amr-sys",
    "symphonia-bundle-evs",
    "voip-replay",
]

[workspace.dependencies]
bindgen = { version = "0.69" }
cc = { version = "1.0", features = ["parallel"] }
