[package]
name = "codec-detector"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
combine = "4.6.7"
fraction = "0.15"
indexmap = "2"
num-derive.workspace = true
num-traits.workspace = true
serde = { version = "1", features = ["derive", "rc"] }
serde_yaml = "0.9"
