[package]
name = "symphonia-codec-opus"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
combine = "4"
thiserror = "1"

[features]
custom-modes = []
fix-point = []
float = []
hardending = []
osce = []

[[example]]
name = "demo"

[dev-dependencies]
clap = "4"
