[package]
name = "opencore-amr-sys"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
anyhow = { workspace = true }
bindgen = { workspace = true, optional = true }
cargo-emit = { workspace = true }

[features]
default = ["gen"]
gen = ["bindgen"]
