[package]
name = "symphonia-bundle-amr"
version = "0.5.3"
edition = "2021"

[dependencies]
bitvec = "1"
byteorder = { workspace = true }
symphonia-core = { workspace = true }

opencore-amr-sys = { path = "../opencore-amr-sys" }

[features]
default = []
gen = ["opencore-amr-sys/gen"]
